### ISSUE TITLE
typo in TaskfMRILevel2.v2.0.sh

### ISSUE THREAD

**Issue by luckydjuju** [Washington-University/Pipelines#11]
l.21:
LevelOnefsfNames=`echo $LevelOnefMRINames | sed 's/@/ /g'`
should be replaced with:
LevelOnefsfNames=`echo $LevelOnefsfNames | sed 's/@/ /g'`

**Comment by luckydjuju** [comment]
relatedly, in TaskfMRIAnalysis.v2.0.sh, l.89:
LevelOnefsfNames=`echo $LevelOnefMRINames | sed 's/ /@/g'`
should be replaced with:
LevelOnefsfNames=`echo $LevelOnefsfNames | sed 's/ /@/g'`

**Comment by tbbrown** [comment]
Thank you for pointing out this error. I have fixed it as you suggested and checked the change into the head of the master branch. This change should be included in the next release. 

Thanks again.
