### ISSUE TITLE
MagnitudeInputName="NONE" causes Error

### ISSUE THREAD

**Issue by dabliss** [Washington-University/Pipelines#12]
`PreFreeSurferPipelineBatch.sh` contains the following comment, just before `MagnitudeInputName` is defined:

    # The MagnitudeInputName variable should be set to a 4D magitude volume 
    # with two 3D timepoints or "NONE" if not used

However, when `MagnitudeInputName` is set to `"NONE"`, the script raises the following error:

    Cannot open volume NONE for reading!

The error occurs on this line of `SiemensFieldMapPreprocessingAll.sh`:

    ${FSLDIR}/bin/fslmaths ${MagnitudeInputName} -Tmean ${WD}/Magnitude

My question is, if I don't want to use `MagnitudeInputName`, which lines of `SiemensFieldMapPreprocessingAll.sh` should I exclude (in addition to the one above)?  Are there lines in other scripts called by `PreFreeSurferPipelineBatch.sh` that I should exclude?

**Comment by glasserm** [comment]
You also need to change this variable:

AvgrdcSTRING="SiemensFieldMap"

To

AvgrdcSTRING="NONE"

**Comment by dabliss** [comment]
Thanks, yep, that did the job for me.
