### ISSUE TITLE
global/scripts/TopupPreprocessingAll.sh is in verbose mode

### ISSUE THREAD

**Issue by reckbo** [Washington-University/Pipelines#20]
Small issue, but this script has verbose mode turned on by default in release 3.14:

    #!/bin/bash
    #set -e
    set -xv

**Comment by coalsont** [comment]
For clarity, are you asking that the next release be less verbose?  Current master has "set -x" after the argument parsing, which is less verbose.  I'm not sure if there is any intended policy of how verbose the scripts are supposed to be, is this causing problems?

**Comment by reckbo** [comment]
Ok, sounds like master is fine, the problem with 'set -x' before the argument parsing was that when you call it with '-h' to see the help you get a bunch of echo messages (which made me think that set -xv was left in by accident during debugging).

**Comment by coalsont** [comment]
I just ran it with -h and got only the help info, no debug output, closing.
