### ISSUE TITLE
FreeSurferNHP.sh

### ISSUE THREAD

**Issue by NPHPAM** [Washington-University/Pipelines#28]
Hi! My name is Pam. I'm working with mri of rhesus monkey, I want to do cortical thickness analysis. The scrip  DistortionCorrectionAndEPIToT1wReg_FLIRTBBRAndFreeSurferBBRbased.sh calls FreeSurferNHP.sh which would really help me for my analysis. Somebody knows how can I get or download it? I really appreciate their help! 

Thanks!!

**Comment by cjdonahue** [comment]
Hi Pam,
I can help you with NHP processing. Contact me at donahuec@wustl.edu to discuss. Thx.
-Chad

**Comment by tbbrown** [comment]
Assume this has been followed up on via separate emails.
