### ISSUE TITLE
Eddy Preprocessing

### ISSUE THREAD

**Issue by reckbo** [Washington-University/Pipelines#29]
Hi,

Can someone confirm that  the eddy preprocessing step will generate the
following combined B0 volume?  It's hard to know for sure just by following
the code.

```
B0 . . B0 . . . . B0  # a positive encoded dwi
b0 . . .  # a negative encoded dwi
=>
B0 B0 b0 # the combined b0's 
```

Thanks,
Ryan

**Comment by glasserm** [comment]
I'm not follow this, and this is a question that might be most productively asked on the HCP-Users mailing list, or perhaps the FSL mailing list (if it is not HCP specific).

**Comment by reckbo** [comment]
It's a question about the output of basic_preproc.sh, specifically the structure of Pos_Neg_B0.nii.gz and whether there can be a different number of B0's contributed from the positive phase encoded DWI and the negative phase encoded DWI.   I sent an email to the HCP-Users mailing list as you suggested.

**Comment by tbbrown** [comment]
Question submitted to HCP-Users mailing list
