### ISSUE TITLE
IcaFixProcessingBatch.sh typo?

### ISSUE THREAD

**Issue by umeboshi7** [Washington-University/Pipelines#31]
For consistency, line 126 of  Pipelines/Examples/Scripts/IcaFixProcessingBatch.sh should probably be either:

`FixScript=${HCPPIPEDIR}/ICAFIX/hcp_fix`
or
`FixScript=${FSL_FIXDIR}/hcp_fix`

**Comment by tbbrown** [comment]
You are correct. I've changed this to:
   `FixScript=${HCPPIPEDIR}/ICAFIX/hcp_fix`
In both IcaFixProcessingBatch.sh and IcaFixProcessingBatch.7T.sh
