### ISSUE TITLE
PostFixBatch.sh

### ISSUE THREAD

**Issue by tetsuyacht** [Washington-University/Pipelines#46]
Two argument names for PostFix.sh are wrong.
[Line 106]
wrong: --fmri-names
right: --fmri-name
[Line 107]
wrong: --highpass
right: --high-pass

Also, I think that "NO" is input to ReUseHighPass (line 83) as default, since ${fMRIName}_Atlas_hp${HighPass}.dtseries.nii does not seem to be created after running IcaFixBatch.sh.

**Comment by glasserm** [comment]
Thanks for pointing these out.  They have been fixed.  I added comments to explain better the usage of ReUseHighPass.
