### ISSUE TITLE
smoothing for grayordinates

### ISSUE THREAD

**Issue by shu-hai** [Washington-University/Pipelines#49]
Hello,
I notice that grayordinates includes both the surface and subcortical voxels.
Now I got some results on grayordinates, and I want to __spatially_ smooth_ the values using Gaussian kernels. 
Do you have any code and example to do such smoothing on _surface vertices_?
Thanks.

**Comment by glasserm** [comment]
Connectome Workbench wb_command -cifti-smoothing

**Comment by shu-hai** [comment]
Hi, glasserm,
I am not so familiar with Connectome Workbench.
If I want to do 4mm FWHM for both surface and subcortical voxels, how to operate it in Connectome Workbench?
Any example code?

**Comment by glasserm** [comment]
I guess you'll just have to become familiar then.  The usage available when you type the above command.  You can download Connectome Workbench from here:

https://www.humanconnectome.org/software/connectome-workbench

Really this forum is only for issues with the pipeline code.  For more general questions like the one you asked, it is better to ask on the hcp-users mailing list:

https://www.humanconnectome.org/contact-us

**Comment by coalsont** [comment]
If you can read bash scripts, here is a line that uses the command:

https://github.com/Washington-University/Pipelines/blob/master/TaskfMRIAnalysis/scripts/TaskfMRILevel1.v2.0.sh#L179

The help info is also available online, see these two pages in particular:

https://www.humanconnectome.org/software/workbench-command/-cifti-smoothing
https://www.humanconnectome.org/software/workbench-command/-arguments-help

As Matt said, though, this issue tracker is intended for reporting problems with the HCP Pipelines scripts themselves, and is not a general help forum.
